services:
  estate:
    container_name: estate
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "1090:1090"
    depends_on:
      datasource:
        condition: service_healthy
    networks:
      - estate
    restart: unless-stopped
    command: [ "sh", "-c", "sleep 30 && /app/chessland" ]

  datasource:
    container_name: estatedb
    image: postgres:16.0
    env_file:
      - infrastructure.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5832:5832"
    networks:
      - estate
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  datasource-administration:
    container_name: estate-administration
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - estate
    restart: unless-stopped

networks:
  estate:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  redis: